name: Build and Deploy

on:
  push:
    branches:
      - believeme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository with full history for diff checks
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 2. Set up Java and Maven environments
      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      # 3. Verify Java and Maven installation
      - name: Verify Java and Maven installation
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -v

      # 4. Run Maven build only if source code has changed
      - name: Build with Maven if source code changed
        run: |
          echo "Checking for changes in source files..."
          if [ -z "${{ github.event.before }}" ]; then
            echo "First push or new branch, running mvn clean install."
            mvn clean install -DskipTests
          else
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'src'; then
              echo "Changes detected in source files, running mvn clean install."
              mvn clean install -DskipTests
            else
              echo "No source code changes, skipping build."
            fi
          fi

      # 5. Verify WAR file creation
      - name: Verify WAR file
        run: |
          if [ -f "target/spring-0.0.1-SNAPSHOT.war" ]; then
            echo "WAR file successfully created"
            ls -l target/spring-0.0.1-SNAPSHOT.war
          else
            echo "WAR file not found!"
            echo "Contents of target directory:"
            ls -l target/
            exit 1
          fi

      # 6. Prepare deploy branch and move WAR file for deployment
      - name: Prepare deploy branch
        run: |
          git config --global user.name "pleasebelieveme"
          git config --global user.email "cain1227@naver.com"

          # Backup the WAR file
          cp target/spring-0.0.1-SNAPSHOT.war /tmp/

          # Switch to deploy branch, create if not exists
          if git show-ref --verify --quiet refs/remotes/origin/deploy; then
            git checkout deploy
          else
            git checkout --orphan deploy
            git rm -rf .
          fi

          # Restore the WAR file to root directory
          cp /tmp/spring-0.0.1-SNAPSHOT.war .

      # 7. Commit and push if there are changes
      - name: Commit and push if there are changes
        run: |
          git add spring-0.0.1-SNAPSHOT.war
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing .war file."
            git commit -m "Deploy Spring Boot build files"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/BranchLunchGach/TasteGuide.git deploy --force
          else
            echo "No changes to commit"
          fi
