name: Build and Deploy

on:
  push:
    branches:
      - main # main에 푸쉬될때 트리거

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. 리포지토리 체크아웃 (Git LFS 활성화)
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true  # Git LFS 활성화

      # 2. Java와 Maven 설치
      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          maven-version: '3.9.9'
          cache: 'maven'

      # 3. application.properties 설정 (GitHub secret로부터)
      - name: Create resources directory and configure application.properties
        run: |
          mkdir -p src/main/resources  # src/main/resources 디렉토리 생성
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
          
      - name: Verify application.properties
        run: cat src/main/resources/application.properties
        
      # 4. Maven 빌드 실행
      - name: Build with Maven
        run: |
          echo "Running mvn clean install to build project..."
          mvn clean install -DskipTests
          echo "Build completed."
      
      # 5. .war 파일 생성 확인
      - name: Verify WAR file location
        run: |
          echo "Checking for .war file in target directory..."
          ls -l target/
          if [ -f "target/spring-0.0.1-SNAPSHOT.war" ]; then
            echo "WAR file found at target/spring-0.0.1-SNAPSHOT.war"
          else
            echo "WAR file not found!"
            exit 1
          fi
      
      # 6. AWS S3에 WAR 파일 업로드
      - name: Upload WAR file to S3
        run: |
          aws s3 cp target/spring-0.0.1-SNAPSHOT.war s3://tasteguide/tasteguide.war
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # 7. EC2에 SSH로 접속하여 S3에서 파일 다운로드 후 Spring Boot 재시작
      - name: Deploy to EC2 and Restart Spring Boot
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          
          # S3에서 WAR 파일 다운로드
          ssh -o StrictHostKeyChecking=no -i private-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            "aws s3 cp s3://tasteguide/tasteguide.war /home/ubuntu/tasteguide.war && \
            sudo systemctl restart springboot"
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
